target_directory_path: "/home/dadyatlova_1/dataset/etts/vk_etts_data"
source_data_directory: "/home/dadyatlova_1/dataset/etts/IEMOCAP"
sessions: ["Session1", "Session2", "Session3", "Session4", "Session5"]
original_speaker_ids: ["0011", "0012", "0013", "0014", "0015", "0016", "0017", "0018", "0019", "0020"]
target_speaker_ids: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10"]
speaker_encodings: ["us-ascii", "utf-16le", "utf-16le", "utf-16le", "us-ascii", "iso-8859-1", "iso-8859-1", "utf-16le", "utf-16le", "us-ascii"]
emotions: ["neu", "ang", "hap", "sad", "sur"]
emotion_ids: [0, 1, 2, 3, 4]
sample_rate: 16000