target_directory_path: "/home/dadyatlova_1/dataset/LJSpeech-1.1/mfa_data/my_corpus"
source_directory_path: "/home/dadyatlova_1/dataset/LJSpeech-1.1"
split_filenames: ["train.txt", "val.txt", "test.txt"]