target_directory_path: "/home/dadyatlova_1/dataset/etts/vk_etts_data"
source_data_directory: "/home/dadyatlova_1/dataset/etts/esd"
original_speaker_ids: [0011, 0012, 0013, 0014, 0015, 0016, 0017, 0018, 0019, 0020]
target_speaker_ids: [01, 02, 03, 04, 05, 06, 07, 08, 09, 10]
emotions: ["Neutral", "Angry", "Happy", "Sad", "Surprise"]
emotion_ids: [0, 1, 2, 3, 4]
target_sr: 16000