target_directory_path: "/root/storage/dasha/data/emo-data/english_esd"
source_data_directory: "/root/storage/dasha/data/emo-data/ESD"
#original_speaker_ids: ["0011", "0012", "0013", "0014", "0015", "0016", "0017", "0018", "0019", "0020"]
#target_speaker_ids: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10"]
speaker_encodings: ["us-ascii", "utf-16le", "utf-16le", "utf-16le", "us-ascii", "iso-8859-1", "iso-8859-1", "utf-16le", "utf-16le", "us-ascii"]
emotions: ["Neutral", "Angry", "Happy", "Sad", "Surprise"]
emotion_ids: [0, 1, 2, 3, 4]
target_sample_rate: 16000