source_wav_directory_path: "/home/dadyatlova_1/dataset/LJSpeech-1.1/mfa_data/converted_numbers_corpus"
target_textgrids_directory_path: "/home/dadyatlova_1/dataset/LJSpeech-1.1/mfa_data/aligned_corpus"